### PR TITLE
feat: use codename for flavors

### LINKED ISSUE #9: Remove flavors

### PR DESCRIPTION
**Pull request by viceice**
* replace ubuntu flavor version with codename

closes #9

### CODE REVIEW

**Comment by viceice** [comment]
@rarkins can we publish the flavors with ubuntu codename?

**Comment by viceice** [comment]
So we release following tags now:
* `1.43.1` build from `buildpack:2-rust` (whatever version this is)
* `1.43.1-bionic` from `buildpack:2-rust-18.04
* `1.43.1-focal` from `buildpack:2-rust-20.04

 (will update buildpack to release with codename too later)

**Comment by viceice** [comment]
image

**Comment by viceice** [comment]
@rarkins anything missing here?

**Comment by rarkins** [comment]
Looks good

**Pull request merged**
